################################################################################
# Environment Setup
################################################################################

DOTFILES="$HOME/dotfiles"
DOTFILES_ZSH="$DOTFILES/configurations/common/zsh"