#! /usr/bin/env bash
set -e
shopt -s extglob

branch_name="$(git symbolic-ref --short HEAD 2>/dev/null || true)"
if [[ "$branch_name" =~ ^((.+-)?([A-Z]+-[0-9]+)(-.+)?)$ ]]; then
  ticket="${BASH_REMATCH[3]}"
  if [[ "$(grep "^[^#]" "$1" | grep "\S")" == "[Ticket: ${ticket}]" ]]; then
    echo "ERROR: No commit message provided." >&2
    exit 1
  elif ! grep -Fq "$ticket" "$1"; then
    printf '%s\n\n[Ticket: %s]\n' "$(cat "$1")" "$ticket" > "$1"
  fi
fi