#! /usr/bin/env bash
set -e
shopt -s extglob

if [ -n "$2" ]; then exit; fi
branch_name="$(git symbolic-ref --short HEAD 2>/dev/null || true)"
if [[ "$branch_name" =~ ^((.+-)?([A-Z]+-[0-9]+)(-.+)?)$ ]]; then
  ticket="${BASH_REMATCH[3]}"
  printf '\n\n[Ticket: %s]\n%s' "$ticket" "$(cat "$1")" > "$1"
fi